/**
 * Canonical error codes for SeqCraft domain operations, application commands,
 * and WebMCP tool executions.
 */

export const ERROR_CODES = {
  // Document & Workspace errors
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  NO_ACTIVE_DOCUMENT: 'NO_ACTIVE_DOCUMENT',
  INVALID_DOCUMENT_NAME: 'INVALID_DOCUMENT_NAME',
  DUPLICATE_DOCUMENT_NAME: 'DUPLICATE_DOCUMENT_NAME',
  INVALID_TOPOLOGY: 'INVALID_TOPOLOGY',
  EMPTY_SEQUENCE: 'EMPTY_SEQUENCE',
  INVALID_SEQUENCE: 'INVALID_SEQUENCE',

  // Feature & Annotation errors
  FEATURE_NOT_FOUND: 'FEATURE_NOT_FOUND',
  INVALID_FEATURE_TYPE: 'INVALID_FEATURE_TYPE',
  INVALID_FEATURE_COORDINATES: 'INVALID_FEATURE_COORDINATES',
  INVALID_INDEX: 'INVALID_INDEX',

  // Primer errors
  PRIMER_NOT_FOUND: 'PRIMER_NOT_FOUND',
  INVALID_PRIMER_SEQUENCE: 'INVALID_PRIMER_SEQUENCE',
  NO_AMPLICON_FOUND: 'NO_AMPLICON_FOUND',

  // Coordinate & Selection errors
  INVALID_COORDINATES: 'INVALID_COORDINATES',
  OUT_OF_BOUNDS: 'OUT_OF_BOUNDS',
  NO_SELECTION: 'NO_SELECTION',

  // Enzymatic & Cloning errors
  UNKNOWN_ENZYME: 'UNKNOWN_ENZYME',
  ENZYME_NOT_FOUND: 'ENZYME_NOT_FOUND',
  NO_SITES_FOUND: 'NO_SITES_FOUND',
  INSUFFICIENT_FRAGMENTS: 'INSUFFICIENT_FRAGMENTS',
  ASSEMBLY_FAILED: 'ASSEMBLY_FAILED',
  CLONE_FAILED: 'CLONE_FAILED',
  VECTOR_DOCUMENT_NOT_FOUND: 'VECTOR_DOCUMENT_NOT_FOUND',
  INSERT_DOCUMENT_NOT_FOUND: 'INSERT_DOCUMENT_NOT_FOUND',

  // Transaction & History errors
  NO_PENDING_TRANSACTION: 'NO_PENDING_TRANSACTION',
  TRANSACTION_REJECTED: 'TRANSACTION_REJECTED',
  STALE_TRANSACTION: 'STALE_TRANSACTION',
  STALE_CANDIDATE: 'STALE_CANDIDATE',
  NO_HISTORY: 'NO_HISTORY',
  CANNOT_UNDO: 'CANNOT_UNDO',
  CANNOT_REDO: 'CANNOT_REDO',

  // IO & Automation errors
  UNKNOWN_FORMAT: 'UNKNOWN_FORMAT',
  UNSUPPORTED_FORMAT: 'UNSUPPORTED_FORMAT',
  IMPORT_FAILED: 'IMPORT_FAILED',
  EXPORT_FAILED: 'EXPORT_FAILED',
  PROTOCOL_GENERATION_FAILED: 'PROTOCOL_GENERATION_FAILED',

  // WebMCP & General errors
  UNKNOWN_TOOL: 'UNKNOWN_TOOL',
  INVALID_INPUT: 'INVALID_INPUT',
  ABORTED: 'ABORTED',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;

export type SeqCraftErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
