export interface OpentronsPCRParams {
  protocolName?: string;
  author?: string;
  description?: string;
  apiLevel?: string;
  robotModel?: "OT-2" | "Flex";
  templateDocName: string;
  forwardPrimerName: string;
  reversePrimerName: string;
  ampliconLengthBp: number;
  annealingTempC: number;
  numReactions: number;
  reactionVolumeUl?: number;
  templateVolumeUl?: number;
  fwdPrimerVolumeUl?: number;
  revPrimerVolumeUl?: number;
  masterMixVolumeUl?: number;
}

export interface OpentronsDigestParams {
  protocolName?: string;
  author?: string;
  description?: string;
  apiLevel?: string;
  robotModel?: "OT-2" | "Flex";
  dnaDocName: string;
  enzymeNames: string[];
  incubationTempC?: number;
  incubationTimeMin?: number;
  numReactions: number;
  reactionVolumeUl?: number;
  dnaVolumeUl?: number;
  enzymeVolumeUl?: number;
  bufferVolumeUl?: number;
}

export interface OpentronsProtocolResult {
  pythonCode: string;
  filename: string;
  reagentPlateMap: Record<string, string>;
  tubeRackMap: Record<string, string>;
  billOfMaterials: Array<{ item: string; quantity: string; notes: string }>;
  summary: string;
}

export function compileOpentronsPCRProtocol(params: OpentronsPCRParams): OpentronsProtocolResult {
  const protocolName = params.protocolName || ("PCR Setup - " + params.templateDocName);
  const author = params.author || "SeqCraft Bio-CAD";
  const description = params.description || ("Automated PCR setup for " + params.templateDocName + " with " + params.forwardPrimerName + " and " + params.reversePrimerName);
  const apiLevel = params.apiLevel || "2.15";
  const numReactions = Math.max(1, Math.min(params.numReactions, 96));
  
  const reactionVolumeUl = params.reactionVolumeUl ?? 50;
  const masterMixVolumeUl = params.masterMixVolumeUl ?? 25;
  const fwdPrimerVolumeUl = params.fwdPrimerVolumeUl ?? 2.5;
  const revPrimerVolumeUl = params.revPrimerVolumeUl ?? 2.5;
  const templateVolumeUl = params.templateVolumeUl ?? 2;
  
  const waterVolumeUl = Math.max(0, reactionVolumeUl - (masterMixVolumeUl + fwdPrimerVolumeUl + revPrimerVolumeUl + templateVolumeUl));
  const extensionTimeSec = Math.max(15, Math.ceil((params.ampliconLengthBp / 1000) * 30));
  const annealingTemp = Math.round(params.annealingTempC * 10) / 10;
  
  const tubeRackMap: Record<string, string> = {
    "A1": "Nuclease-free Water (dH2O)",
    "A2": "2X PCR Master Mix (Taq/Q5/Phusion)",
    "A3": "Forward Primer: " + params.forwardPrimerName + " (10 uM)",
    "A4": "Reverse Primer: " + params.reversePrimerName + " (10 uM)",
    "B1": "Template DNA: " + params.templateDocName,
  };

  const reagentPlateMap: Record<string, string> = {};
  const rows = ["A", "B", "C", "D", "E", "F", "G", "H"];
  for (let i = 0; i < numReactions; i++) {
    const r = rows[i % 8];
    const c = Math.floor(i / 8) + 1;
    const well = r + c;
    reagentPlateMap[well] = "PCR Reaction " + (i + 1) + " (" + params.templateDocName + ")";
  }

  const overageMultiplier = 1.10;
  const totalWaterNeeded = Math.round(waterVolumeUl * numReactions * overageMultiplier);
  const totalMMNeeded = Math.round(masterMixVolumeUl * numReactions * overageMultiplier);
  const totalFwdNeeded = Math.round(fwdPrimerVolumeUl * numReactions * overageMultiplier);
  const totalRevNeeded = Math.round(revPrimerVolumeUl * numReactions * overageMultiplier);

  const billOfMaterials = [
    { item: "Nuclease-free Water", quantity: totalWaterNeeded + " uL", notes: "Place in Tube A1" },
    { item: "2X PCR Master Mix", quantity: totalMMNeeded + " uL", notes: "Place in Tube A2" },
    { item: params.forwardPrimerName + " (10 uM)", quantity: totalFwdNeeded + " uL", notes: "Place in Tube A3" },
    { item: params.reversePrimerName + " (10 uM)", quantity: totalRevNeeded + " uL", notes: "Place in Tube A4" },
    { item: "Template DNA (" + params.templateDocName + ")", quantity: Math.round(templateVolumeUl * numReactions * 1.15) + " uL", notes: "Place in Tube B1" },
    { item: "96-Well PCR Plate", quantity: "1 plate", notes: "NEST 0.1 mL full skirt in Slot 7 or Thermocycler" },
    { item: "20 uL Filter Tips", quantity: Math.ceil((numReactions * 5) / 96) + " rack(s)", notes: "Slot 1" },
  ];

  const wellsList = Object.keys(reagentPlateMap).map(w => String.fromCharCode(39) + w + String.fromCharCode(39)).join(", ");

  const pythonCode = [
    String.fromCharCode(34, 34, 34),
    protocolName,
    "Author: " + author,
    "Description: " + description,
    "Generated by SeqCraft In-Silico Bio-CAD",
    String.fromCharCode(34, 34, 34),
    "from opentrons import protocol_api",
    "",
    "metadata = {",
    "    " + String.fromCharCode(39) + "protocolName" + String.fromCharCode(39) + ": " + String.fromCharCode(39) + protocolName + String.fromCharCode(39) + ",",
    "    " + String.fromCharCode(39) + "author" + String.fromCharCode(39) + ": " + String.fromCharCode(39) + author + String.fromCharCode(39) + ",",
    "    " + String.fromCharCode(39) + "description" + String.fromCharCode(39) + ": " + String.fromCharCode(39) + description + String.fromCharCode(39) + ",",
    "    " + String.fromCharCode(39) + "apiLevel" + String.fromCharCode(39) + ": " + String.fromCharCode(39) + apiLevel + String.fromCharCode(39),
    "}",
    "",
    "def run(protocol: protocol_api.ProtocolContext):",
    "    tiprack_20 = protocol.load_labware(" + String.fromCharCode(39) + "opentrons_96_tiprack_20ul" + String.fromCharCode(39) + ", " + String.fromCharCode(39) + "1" + String.fromCharCode(39) + ")",
    "    p20 = protocol.load_instrument(" + String.fromCharCode(39) + "p20_single_gen2" + String.fromCharCode(39) + ", " + String.fromCharCode(39) + "right" + String.fromCharCode(39) + ", tip_racks=[tiprack_20])",
    "",
    "    tuberack = protocol.load_labware(" + String.fromCharCode(39) + "opentrons_24_tuberack_generic_2ml_screwcap" + String.fromCharCode(39) + ", " + String.fromCharCode(39) + "6" + String.fromCharCode(39) + ")",
    "    water = tuberack[" + String.fromCharCode(39) + "A1" + String.fromCharCode(39) + "]",
    "    master_mix = tuberack[" + String.fromCharCode(39) + "A2" + String.fromCharCode(39) + "]",
    "    fwd_primer = tuberack[" + String.fromCharCode(39) + "A3" + String.fromCharCode(39) + "]",
    "    rev_primer = tuberack[" + String.fromCharCode(39) + "A4" + String.fromCharCode(39) + "]",
    "    template_dna = tuberack[" + String.fromCharCode(39) + "B1" + String.fromCharCode(39) + "]",
    "",
    "    pcr_plate = protocol.load_labware(" + String.fromCharCode(39) + "nest_96_wellplate_100ul_pcr_full_skirt" + String.fromCharCode(39) + ", " + String.fromCharCode(39) + "7" + String.fromCharCode(39) + ")",
    "    reaction_wells = [pcr_plate[well] for well in [" + wellsList + "]]",
    "",
    waterVolumeUl > 0 ? [
      "    protocol.comment(\"Distributing " + waterVolumeUl + " uL of nuclease-free water...\")",
      "    p20.pick_up_tip()",
      "    for well in reaction_wells:",
      "        p20.aspirate(" + waterVolumeUl + ", water)",
      "        p20.dispense(" + waterVolumeUl + ", well)",
      "    p20.drop_tip()"
    ].join("\n") : "    # No water required",
    "",
    "    protocol.comment(\"Distributing " + masterMixVolumeUl + " uL of 2X Master Mix...\")",
    "    for well in reaction_wells:",
    "        p20.pick_up_tip()",
    "        p20.aspirate(" + masterMixVolumeUl + ", master_mix)",
    "        p20.dispense(" + masterMixVolumeUl + ", well)",
    "        p20.drop_tip()",
    "",
    "    protocol.comment(\"Adding " + fwdPrimerVolumeUl + " uL of Forward Primer (" + params.forwardPrimerName + ")...\")",
    "    for well in reaction_wells:",
    "        p20.pick_up_tip()",
    "        p20.aspirate(" + fwdPrimerVolumeUl + ", fwd_primer)",
    "        p20.dispense(" + fwdPrimerVolumeUl + ", well)",
    "        p20.drop_tip()",
    "",
    "    protocol.comment(\"Adding " + revPrimerVolumeUl + " uL of Reverse Primer (" + params.reversePrimerName + ")...\")",
    "    for well in reaction_wells:",
    "        p20.pick_up_tip()",
    "        p20.aspirate(" + revPrimerVolumeUl + ", rev_primer)",
    "        p20.dispense(" + revPrimerVolumeUl + ", well)",
    "        p20.drop_tip()",
    "",
    "    protocol.comment(\"Adding " + templateVolumeUl + " uL of Template DNA (" + params.templateDocName + ") and mixing...\")",
    "    for well in reaction_wells:",
    "        p20.pick_up_tip()",
    "        p20.aspirate(" + templateVolumeUl + ", template_dna)",
    "        p20.dispense(" + templateVolumeUl + ", well)",
    "        p20.mix(3, 10, well)",
    "        p20.drop_tip()",
    "",
    "    protocol.comment(\"PCR reaction setup complete.\")",
    "    protocol.comment(\"Thermocycler profile: 95C 2m -> 30x (95C 30s, " + annealingTemp + "C 30s, 72C " + extensionTimeSec + "s) -> 72C 5m -> 4C hold\")",
    ""
  ].join("\n");

  return {
    pythonCode,
    filename: "opentrons_pcr_" + params.templateDocName.toLowerCase().replace(/[^a-z0-9]/g, "_") + ".py",
    reagentPlateMap,
    tubeRackMap,
    billOfMaterials,
    summary: "Compiled Opentrons PCR protocol for " + numReactions + " reaction(s) (" + params.templateDocName + " with " + params.forwardPrimerName + "/" + params.reversePrimerName + ", Ta=" + annealingTemp + "C, ext=" + extensionTimeSec + "s)"
  };
}

export function compileOpentronsDigestProtocol(params: OpentronsDigestParams): OpentronsProtocolResult {
  const protocolName = params.protocolName || ("Restriction Digest - " + params.dnaDocName);
  const author = params.author || "SeqCraft Bio-CAD";
  const description = params.description || ("Automated restriction digest setup for " + params.dnaDocName + " using " + params.enzymeNames.join(", "));
  const apiLevel = params.apiLevel || "2.15";
  const numReactions = Math.max(1, Math.min(params.numReactions, 96));
  
  const reactionVolumeUl = params.reactionVolumeUl ?? 50;
  const dnaVolumeUl = params.dnaVolumeUl ?? 10;
  const bufferVolumeUl = params.bufferVolumeUl ?? 5;
  const enzymeVolumeUl = params.enzymeVolumeUl ?? 1;
  const totalEnzymeVolume = enzymeVolumeUl * params.enzymeNames.length;
  
  const waterVolumeUl = Math.max(0, reactionVolumeUl - (dnaVolumeUl + bufferVolumeUl + totalEnzymeVolume));
  const incubationTemp = params.incubationTempC ?? 37;
  const incubationTimeMin = params.incubationTimeMin ?? 60;

  const tubeRackMap: Record<string, string> = {
    "A1": "Nuclease-free Water",
    "A2": "10X Restriction Buffer",
    "B1": "Substrate DNA: " + params.dnaDocName,
  };

  params.enzymeNames.forEach((name, i) => {
    tubeRackMap["A" + (i + 3)] = "Restriction Enzyme: " + name;
  });

  const reagentPlateMap: Record<string, string> = {};
  const rows = ["A", "B", "C", "D", "E", "F", "G", "H"];
  for (let i = 0; i < numReactions; i++) {
    const r = rows[i % 8];
    const c = Math.floor(i / 8) + 1;
    const well = r + c;
    reagentPlateMap[well] = "Digest " + (i + 1) + " (" + params.dnaDocName + " + " + params.enzymeNames.join("/") + ")";
  }

  const billOfMaterials = [
    { item: "Nuclease-free Water", quantity: Math.round(waterVolumeUl * numReactions * 1.10) + " uL", notes: "Tube A1" },
    { item: "10X Restriction Buffer", quantity: Math.round(bufferVolumeUl * numReactions * 1.10) + " uL", notes: "Tube A2" },
    ...params.enzymeNames.map((name, i) => ({
      item: "Enzyme: " + name,
      quantity: Math.round(enzymeVolumeUl * numReactions * 1.20) + " uL",
      notes: "Tube A" + (i + 3) + " (Keep chilled on ice/cold block)"
    })),
    { item: "Substrate DNA (" + params.dnaDocName + ")", quantity: Math.round(dnaVolumeUl * numReactions * 1.10) + " uL", notes: "Tube B1" },
    { item: "96-Well PCR/Reaction Plate", quantity: "1 plate", notes: "Slot 7" },
    { item: "20 uL Filter Tips", quantity: Math.ceil((numReactions * (3 + params.enzymeNames.length)) / 96) + " rack(s)", notes: "Slot 1" },
  ];

  const wellsList = Object.keys(reagentPlateMap).map(w => String.fromCharCode(39) + w + String.fromCharCode(39)).join(", ");

  const pythonCode = [
    String.fromCharCode(34, 34, 34),
    protocolName,
    "Author: " + author,
    "Description: " + description,
    "Generated by SeqCraft In-Silico Bio-CAD",
    String.fromCharCode(34, 34, 34),
    "from opentrons import protocol_api",
    "",
    "metadata = {",
    "    " + String.fromCharCode(39) + "protocolName" + String.fromCharCode(39) + ": " + String.fromCharCode(39) + protocolName + String.fromCharCode(39) + ",",
    "    " + String.fromCharCode(39) + "author" + String.fromCharCode(39) + ": " + String.fromCharCode(39) + author + String.fromCharCode(39) + ",",
    "    " + String.fromCharCode(39) + "description" + String.fromCharCode(39) + ": " + String.fromCharCode(39) + description + String.fromCharCode(39) + ",",
    "    " + String.fromCharCode(39) + "apiLevel" + String.fromCharCode(39) + ": " + String.fromCharCode(39) + apiLevel + String.fromCharCode(39),
    "}",
    "",
    "def run(protocol: protocol_api.ProtocolContext):",
    "    tiprack_20 = protocol.load_labware(" + String.fromCharCode(39) + "opentrons_96_tiprack_20ul" + String.fromCharCode(39) + ", " + String.fromCharCode(39) + "1" + String.fromCharCode(39) + ")",
    "    p20 = protocol.load_instrument(" + String.fromCharCode(39) + "p20_single_gen2" + String.fromCharCode(39) + ", " + String.fromCharCode(39) + "right" + String.fromCharCode(39) + ", tip_racks=[tiprack_20])",
    "",
    "    tuberack = protocol.load_labware(" + String.fromCharCode(39) + "opentrons_24_tuberack_generic_2ml_screwcap" + String.fromCharCode(39) + ", " + String.fromCharCode(39) + "6" + String.fromCharCode(39) + ")",
    "    water = tuberack[" + String.fromCharCode(39) + "A1" + String.fromCharCode(39) + "]",
    "    buffer = tuberack[" + String.fromCharCode(39) + "A2" + String.fromCharCode(39) + "]",
    "    dna = tuberack[" + String.fromCharCode(39) + "B1" + String.fromCharCode(39) + "]",
    ...params.enzymeNames.map((_, i) => "    enzyme_" + (i + 1) + " = tuberack[" + String.fromCharCode(39) + "A" + (i + 3) + String.fromCharCode(39) + "]"),
    "",
    "    digest_plate = protocol.load_labware(" + String.fromCharCode(39) + "nest_96_wellplate_100ul_pcr_full_skirt" + String.fromCharCode(39) + ", " + String.fromCharCode(39) + "7" + String.fromCharCode(39) + ")",
    "    reaction_wells = [digest_plate[well] for well in [" + wellsList + "]]",
    "",
    "    # Step 1: Add Water",
    "    protocol.comment(\"Distributing " + waterVolumeUl + " uL water...\")",
    "    p20.pick_up_tip()",
    "    for well in reaction_wells:",
    "        p20.aspirate(" + waterVolumeUl + ", water)",
    "        p20.dispense(" + waterVolumeUl + ", well)",
    "    p20.drop_tip()",
    "",
    "    # Step 2: Add 10X Buffer",
    "    protocol.comment(\"Distributing " + bufferVolumeUl + " uL 10X Buffer...\")",
    "    for well in reaction_wells:",
    "        p20.pick_up_tip()",
    "        p20.aspirate(" + bufferVolumeUl + ", buffer)",
    "        p20.dispense(" + bufferVolumeUl + ", well)",
    "        p20.drop_tip()",
    "",
    "    # Step 3: Add Substrate DNA",
    "    protocol.comment(\"Adding " + dnaVolumeUl + " uL Substrate DNA (" + params.dnaDocName + ")...\")",
    "    for well in reaction_wells:",
    "        p20.pick_up_tip()",
    "        p20.aspirate(" + dnaVolumeUl + ", dna)",
    "        p20.dispense(" + dnaVolumeUl + ", well)",
    "        p20.drop_tip()",
    "",
    "    # Step 4: Add Enzymes",
    ...params.enzymeNames.map((name, i) => [
      "    protocol.comment(\"Adding " + enzymeVolumeUl + " uL of Enzyme " + name + "...\")",
      "    for well in reaction_wells:",
      "        p20.pick_up_tip()",
      "        p20.aspirate(" + enzymeVolumeUl + ", enzyme_" + (i + 1) + ")",
      "        p20.dispense(" + enzymeVolumeUl + ", well)",
      "        p20.mix(2, 10, well)",
      "        p20.drop_tip()"
    ].join("\n")),
    "",
    "    protocol.comment(\"Digestion setup complete.\")",
    "    protocol.comment(\"Incubate at " + incubationTemp + " C for " + incubationTimeMin + " minutes.\")",
    ""
  ].join("\n");

  return {
    pythonCode,
    filename: "opentrons_digest_" + params.dnaDocName.toLowerCase().replace(/[^a-z0-9]/g, "_") + ".py",
    reagentPlateMap,
    tubeRackMap,
    billOfMaterials,
    summary: "Compiled Opentrons restriction digest protocol for " + numReactions + " reaction(s) (" + params.dnaDocName + " with " + params.enzymeNames.join(", ") + " at " + incubationTemp + "C for " + incubationTimeMin + "m)"
  };
}
